learners:
  api:
    url: http://localhost:8083

sms:
  gateway:
    url: http://localhost:8083

ftp:
  host: localhost
  port: 2222
  username: user
  password: password

SERVICE_BASE_URL: http://localhost:${PORT}