spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;database=tempdb
    username: sa
    password: s?u!ERe3i4ok=58drAsw
    hikari:
      minimum-idle: 25
      maximum-pool-size: 25

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dbo
        dialect: org.hibernate.dialect.SQLServer2012Dialect
logging:
  level:
    org:
      springframework: INFO