server:
  port: ${PORT}

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${JDBC_URL:jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;database=tempdb}
    jdbc-url: ${spring.datasource.url}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:s?u!ERe3i4ok=58drAsw}
    hikari:
      connection-timeout: 300000
      minimum-idle: 25
      maximum-pool-size: 25
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dbo
        dialect: org.hibernate.dialect.SQLServerDialect
  boot:
    admin:
      client:
        username: ${SPRING_BOOT_ADMIN_USERNAME:admin}
        password: ${SPRING_BOOT_ADMIN_PASSWORD:password}
        url: ${SPRING_BOOT_ADMIN_URL:http://localhost:8082}
        instance:
          service-url: ${SERVICE_BASE_URL}/
          base-service-url: ${SERVICE_BASE_URL}/
          management-url: ${SERVICE_BASE_URL}/actuator
          health-url: ${SERVICE_BASE_URL}/actuator/health
  mail:
    host: smtp.gmail.com
    port: 587
    username: cbac4c@gmail.com
    password: 'tzfm mjea mbgk maoh'
    from-address: mthoko78@gmail.com
    smtp:
      auth: true
      timeout: 5000
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
        debug: false

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    env:
      show-values: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework: INFO

springdoc:
  api-docs:
    path: /api-docs

clickatel:
  sms:
    apiKey: 3D_dkMvfQ1SA-4a0NE13oQ==
    defaultRecipient: 27684243087
    url: https://platform.clickatell.com/messages/http/send

firebase:
  accessToken: AIzaSyD9lDylJbFAjDtW0AaeGcK8Jpc2S44HY4Y

gcp:
  firebase:
    service-account: 'classpath:firebase-service-account.json'
    host: ${FIREBASE_HOST:http://localhost:9000}

ftp:
  baseDir: /upload/
  documents: documents

geo:
  api:
    url: http://mapquestapi.com?key=${geo.api.key}&includeRoadMetadata=${geo.api.includeRoadMetadata}&includeNearestIntersection=${geo.api.includeNearestIntersection}
    key: YVT9TNokVXCI5A7TaC88zcTYEzwLVz5A
    includeRoadMetadata: true
    includeNearestIntersection: true

sms:
  apiKey: 4f5b7d6e
  apiSecret: UWeZlAcFoJYNE5FJ
  defaultRecipient: 27684243087
  verificationPhrase: <#> Your verification code is

ngrok:
  version: "2"