spring:
  datasource:
    url: jdbc:sqlserver://mthoko78.mssql.somee.com;database=mthoko78;encrypt=true;trustServerCertificate=true
    username: mhlangamthoko_SQLLogin_1
    password: l15j9v8w5u

  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: mthoko78@outlook.com
    password: Smj@dbn1
    debug: true
    transport:
      protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

PORT: 5000
EPIZY: http://mthokozisi.epizy.com/service/monitor.php

ftp:
  host: ftpupload.net
  port: 21
  username: epiz_24456977
  password: Qfniw5vLxB7
  baseDir: /htdocs/
  base_directory: /htdocs/uploads/general/
  calls_directory: /htdocs/uploads/calls/
  service_directory: /htdocs/uploads/service/
  base_url: EPIZY

sms:
  verificationPhrase: <#> Your verification code is

learners:
  api:
    url: https://learners-drivers-api.herokuapp.com/
