spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=tempDb
    password: guest_password
gcp:
  firebase:
    host: http://localhost:9000