spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  rabbitmq:
    host: ${RABBIT_HOST:rat-01.rmq2.cloudamqp.com}
#    port: 5672
    username: ${RABBIT_USERNAME:ilgcrswn}
    password: ${RABBIT_PASSWORD:38e4dJGc_92brDNOLtYv0lZ_asDiqpY4}
    template:
      routing-key: ${RABBIT_ROUTING_KEY:chess_game}
    virtual-host: ${RABBIT_VIRTUAL_HOST:ilgcrswn}

server:
  session:
    cookie:
      max-age: 10
  servlet:
    session:
      timeout: 10s
      cookie:
        http-only: false
        secure: false

environment: remote