spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://0.tcp.in.ngrok.io:14205;encrypt=true;trustServerCertificate=true;database=tempdb
    username: ${DATABASE_USERNAME:sa}
    password: "s?u!ERe3i4ok=58drAsw"
    hikari:
      connection-timeout: 300000
      minimum-idle: 25
      maximum-pool-size: 25
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

PORT: 9085
DATABASE_PASSWORD: AVNS_X1TOnuPaZlWwjkcYSit