spring:
  datasource:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        default_schema: PUBLIC
        dialect: org.hibernate.dialect.H2Dialect

JDBC_URL: jdbc:h2:file:./src/main/resources/bible;MODE=MSSQLServer;DB_CLOSE_ON_EXIT=FALSE;TRACE_LEVEL_FILE=0
DATABASE_PASSWORD:
FIREBASE_HOST: https://61bd-41-25-43-89.ngrok-free.app
SPRING_BOOT_ADMIN_URL: https://7377-41-25-43-89.ngrok-free.app
SERVICE_BASE_URL: https://bible-core.herokuapp.com/